#!/bin/sh

EXPECTED="$1"
ACTUAL="$2"

if [ "$EXPECTED" == "$ACTUAL" ]; then
  echo "::error::Not expected '$EXPECTED'"
  exit 1
fi

echo "::debug::Non-equality check passes with '$EXPECTED' and '$ACTUAL'"
