name: Test if the workflow works as intended

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

env:
  CHECKOUT_PATH: source

jobs:
  test:
    strategy:
      matrix:
        include:
          - github-repository: docker-library/hello-world
            dockerhub-repository: my/hello-world
            refs: "[\"480c62c690c0af4427372cf7f0de11da4e00e6c5\"]"
            docker-context: amd64/hello-world
            dockerfile: amd64/hello-world/Dockerfile
            push-image: false
    name: Should successfully build images with given refs
    uses: ./.github/workflows/workflow.yml
    with:
      refs: ${{ matrix.refs }}
      github-repository: ${{ matrix.github-repository }}
      dockerhub-repository: ${{ matrix.dockerhub-repository }}
      pre-build-script: |
        ls "$CHECKOUT_PATH"
      post-build-script: |
        ./scripts/verify_image '-d' $IMAGE:$TAG ''
      push-image: ${{ inputs.push-image == 'true' || inputs.push-image == true }}
      platforms: linux/amd64
      docker-context: ${{ matrix.docker-context }}
      dockerfile: ${{ matrix.dockerfile }}
