name: Test if the workflow works as intended

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

env:
  CHECKOUT_PATH: source
  VERIFY_IMAGE: ./scripts/verify_image

jobs:
  test:
    strategy:
      matrix:
        include:
          - github-repository: docker-library/hello-world
            dockerhub-repository: my/hello-world
            tags: "[\"master\"]"
            docker-context: amd64/hello-world
            dockerfile: amd64/hello-world/Dockerfile
            push-image: false
    name: Should successfully build images with given tags
    uses: ./.github/workflows/workflow.yml
    with:
      tags: ${{ matrix.tags }}
      github-repository: ${{ matrix.github-repository }}
      dockerhub-repository: ${{ matrix.dockerhub-repository }}
      pre-build-script: |
        ls -R "$CHECKOUT_PATH"
      post-build-script: |
        $VERIFY_IMAGE '-d' $IMAGE:$TAG ''
      push-image: ${{ inputs.push-image == 'true' || inputs.push-image == true }}
      platforms: linux/amd64
      docker-context: ${{ matrix.docker-context }}
      dockerfile: ${{ matrix.dockerfile }}
